name: Publish Package to OSS Sonatype Repository
on:
  push:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y gnupg2

      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Perform Tests
        run: gradle check

      - name: Install GPG Secret Key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import && \
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish Package
        run: |
          gradle publish \
            -PossrhUsername=${{ secrets.OSSRH_USERNAME }} \
            -PossrhPassword=${{ secrets.OSSRH_TOKEN }} \
            -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_KEY }} \
            -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
